### ISSUE TITLE
Read out option for the translation and adding icons for the social media handles and adding a night mode

### ISSUE THREAD

**Issue by santhos-13** [zabihhaqqani/numbers2text#7]

**Comment by santhos-13** [comment]
i will work on this. can you assign this to me under label hacktoberfest????

**Comment by zabihhaqqani** [comment]
the issues are already there try to work on other issues.

**Comment by santhos-13** [comment]
but all the isuues are closed already in this repo.

**Comment by zabihhaqqani** [comment]
you can create a new issue and work on it or check out other repos on my profile to contribute they are also beginner friendly.
